echo //generated by file create_version_h.bat > version.h

IF "%APPVEYOR_BUILD_VERSION%"=="" (
	echo build not in appveyor
) ELSE (
	git tag %APPVEYOR_BUILD_VERSION%
)


FOR /F "tokens=*" %%a in ('call git describe --tags --long') do (
		echo #define GIT_VERSION "%%a" > version.h
)