#!/bin/sh -e

# Create a udev rules file
sudo echo "SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"0403\", ATTRS{idProduct}==\"6011\", GROUP=\"dialout\", MODE=\"0660\"" > "/etc/udev/rules.d/bcu-nxp-ftdi.rules"